---
title: 'Meet the Decodable Crew At Kafka Summit London 2024!'
date: "2024-03-14T00:00:00+00:00"
draft: true
markup: adoc
canonical_url: https://www.decodable.co/blog/meet-decodable-at-kafka-summit-london-2024
---
:source-highlighter: rouge
:rouge-style: base16.dark
:icons: font
:imagesdir: /images
ifdef::env-github[]
:imagesdir: ../../static/images
endif::[]

_This post originally appeared on the link:https://www.decodable.co/blog/meet-decodable-at-kafka-summit-london-2024[Decodable blog]._

It’s just a few more days until one of the key events of the year in the data streaming space:  link:https://www.kafka-summit.org/events/kafka-summit-london-2024/about[Kafka Summit London] !
Of course we wouldn’t miss this opportunity for meeting the data community, talking about the latest developments and product news here at Decodable, learning about your requirements, and exchanging with all you data practitioners at large.
So if you are at Kafka Summit next week, make sure to catch one of our talks, stop by at the booth, or even do your own lightning talk at a meet-up after the event.
Here are some of the things we have planned.
We’d love to see you next week!

<!--more-->

=== Talks
The key part to every conference are breakout sessions and lightning talks, and we’re excited to be present at Kafka Summit London with the following sessions this year:

* Robin Moffatt:  link:https://events.bizzabo.com/559905/agenda/session/1284897%20/[🐲 Here be Stacktraces — Flink SQL for Non-Java Developers]  / Tue Mar 19 3:30 PM
* Gunnar Morling:  link:https://events.bizzabo.com/559905/agenda/session/1284970[Data Contracts In Practice With Debezium and Apache Flink]  / Wed Mar 20, 1:00 PM
* Sharon Xie:  link:https://events.bizzabo.com/559905/agenda/session/1284949[Timing is Everything: Understanding Event-Time Processing in Flink SQL]  /  Wed Mar 20, 10:00 AM

In addition, Robin and myself will be room hosts on Wednesday.
So if you want to see us MC-ing some other excellent talks, drop by in Breakout Room 2.


=== The Decodable Booth
The booth (#106, very centrally located in the expo area) will be where you can meet the Decodable team during the two conference days.
We’ll do *live demos* of the product and show how easy realtime data movement and processing can be in this time and age.
Bring all your technical (and other) *questions*, we’ll have several folks from the engineering, product, and sales teams.
It’ll be a unique opportunity for discussing how Decodable can help with your data streaming needs.
If you’d like to book a meeting in advance, please fill out  link:https://www.decodable.co/contact[the contact form] , and someone will get back to you for setting this up.
Needless to say there’ll also be some *amazing swag* (rumor has it, our legendary acorns will be back), a *raffle*, and then some.


=== Bring Your Running Shoes 👟
On Tuesday morning there’ll be an unofficial Kafka Summit 5k run (or walk, if you prefer) starting from near the ExCeL center.
Details are TBC - see  link:https://rmoff.net/2022/04/05/the-unofficial-kafka-summit-london-2022-run/walk/[this blog post]  for an idea of how it’s worked in past years, and stay tuned to  link:https://twitter.com/rmoff/[Robin’s Twitter feed]  for details of where & when to meet next Tuesday.


=== Meet-up
Together with the amazing folks from  link:https://aiven.io/[Aiven] , we’re  link:https://www.meetup.com/uk-open-source-data-infrastructure-meetup/events/299077949/[co-hosting a meet-up]  after the event, on Wednesday March 20, 6:00 PM.
There will be lightning talks (up to ten minutes) and some light bites (no pun intended).
Make sure to register on the meet-up page to secure your spot.
Everyone attending is invited to propose their own data-related talk, so if you ever wanted to get your idea, project, or other data topic in front of an audience, this event will be for you.
And if you’d rather just attend for the vibe and listen to the talks, that’s cool too.


=== Product News
Last but not least, there’ll be some really exciting Decodable product news which we are planning to announce in the course of the next few weeks!
Without giving away too much just yet, I think it’s safe to say that realtime data movement and processing, based on proven open-source technologies such as Debezium and Apache Flink, has never been easier.
Decodable is here to help you with propagating your data in the right shape and form to the right locations and systems, in real time, with as little or much processing as needed.
Stay tuned for the details!

Finally, after Kafka Summit will be _before_ Kafka Summit: I am happy to share that we're also planning to be present at the inaugural  link:https://www.kafka-summit.org/events/kafka-summit-bangalore-2024/about[Kafka Summit Bengaluru] .
So mark your calendars for May 2 for that one—can't wait to get to meet the amazing developer community in India at last!