---
title: "Projects"
date: 2019-12-26T10:00:00+01:00
draft: false
type: "page"
---

I have contributed to a wide range of open-source projects over the last years.
Here's a selection of projects I have been involved with.

== Debezium

https://debezium.io[Debezium] is a platform for change data capture;
it lets you stream changes out of different databases such as Postgres, MySQL, MongoDB and SQL Server into Apache Kafka.
I am the current lead of the Debezium project.

== Quarkus

https://quarkus.io/[Quarkus] is a "Kubernetes Native Java stack tailored for OpenJDK HotSpot and GraalVM, crafted from the best of breed Java libraries and standards".
My contributions to Quarkus are centered around its https://quarkus.io/guides/kafka-streams[extension for Kafka Streams],
which I initially created.

== Bean Validation and Hibernate Validator

https://beanvalidation.org/[Bean Validation] is a Java specification which lets you express constraints on object models via annotations.
Originally developed at the JCP, it's now part of the Jakarta EE umbrella at the Eclipse foundation.
I have been the spec lead for Bean Validation 2.0 (JSR 380) and the lead of the reference implementation https://hibernate.org/validator/[Hibernate Validator].

== Other Hibernate Projects

As part of the https://hibernate.org/[Hibernate] team, I've contributed to different projects such as Hibernate OGM (an effort to access NoSQL stores with JPA),
Hibernate Search (full-text search for domain models based on Apache Lucene and Elasticsearch) and Hibernate ORM.

== MapStruct

https://mapstruct.org/[MapStruct] is a compile-time code generator for bean-to-bean mappings.
Based on annotated Java interfaces, MapStruct generates mapping code that it is fully type-safe and very efficient by avoiding any usage of reflection.
I was the creator and initial project lead of MapStruct.

== Deptective and ModiTect

https://github.com/moditect/moditect[ModiTect] is a family of Maven and Gradle plug-ins around the Java Module System,
e.g. for creating module descriptors and building modular runtime images via jlink.
https://github.com/moditect/deptective[Deptective] is a plug-in for the Java compiler (javac) for enforcing package dependencies within Java projects based on a declarative architecture definition.
