---
title: "About Me"
date: 2025-05-02T09:30:00+02:00
draft: false
type: "page"
markup: adoc
---

I am an open-source software engineer in the Java and data streaming space. I currently work as a Technologist at https://www.confluent.io/[Confluent].
In my past role at Decodable I focused on developer outreach and helped them build their stream processing platform based on Apache Flink.
Prior to that, I spent ten years at Red Hat, where I led the Debezium project, a platform for change data capture.

I have been a long-time committer to multiple link:/projects[open-source projects], including Hibernate, kcctl, JfrUnit, MapStruct and Deptective;
I also serve as the spec lead for Bean Validation 2.0 (first at the JCP, now under the Jakarta EE umbrella at the Eclipse Foundation).

Named a https://apex.oracle.com/pls/apex/f?p=19297:3::::::[Java Champion], I enjoy link:/conferences[speaking] at conferences, for instance at QCon, JavaOne, Red Hat Summit, JavaZone, JavaLand and Kafka Summit.

Occasionally, I link:/blog[blog] about topics related to software engineering.

== Speaker Information

The following information can be used on conference websites.

**Head shot:** link:/images/gunnar_morling_500.jpg[500px], link:/images/gunnar_morling_1000.jpg[1000px]

=== 🇬🇧 English

**Title:** Principal Technologist, Confluent

**Bio:** Gunnar Morling is a software engineer and open-source enthusiast by heart, currently working as a Technologist at Confluent. Previously, he helped to build a realtime stream processing platform based on Apache Flink and led the Debezium project, a distributed platform for change data capture. He is a Java Champion and has founded multiple open source projects such as JfrUnit, kcctl, and MapStruct. Gunnar is an avid blogger (morling.dev) and has spoken at various conferences like QCon, Java One, and Devoxx. He lives in Hamburg, Germany.

=== 🇩🇪 Deutsch

**Titel:** Principal Technologist, Confluent

**Bio:** Gunnar Morling ist Softwareentwickler und Open-Source-Enthusiast, gegenwärtig tätig als Technologist für Confluent. Zuvor arbeitete er an einer Plattform für Real-Time Stream Processing basierend auf Apache Flink; weiterhin leitete er das Debezium-Projekt, eine verteilte Lösung für Change Data Capture. Er ist ein Java Champion und hat diverse Open-Source-Projekte wie JfrUnit, kcctl und MapStruct ins Leben gerufen. Gunnar bloggt auf morling.dev und teilt seine Erfahrungen in Vorträgen, u.a. bei JavaLand, QCon, JavaOne und Devoxx. Er lebt und arbeitet in Hamburg.
