---
title: "About Me"
date: 2022-11-22T18:45:00+01:00
draft: false
type: "page"
---

I am an open-source software engineer, currently working at https://www.decodable.co/[Decodable], involved with data streaming based on Apache Flink.
Before joining Decodable, I spent ten years at Red Hat, where I led the Debezium project, a platform for change data capture.

I have been a long-time committer to multiple link:/projects[open-source projects], including Hibernate, kcctl, JfrUnit, MapStruct and Deptective;
I also serve as the spec lead for Bean Validation 2.0 (first at the JCP, now under the Jakarta EE umbrella at the Eclipse Foundation).

Named a https://apex.oracle.com/pls/apex/f?p=19297:3::::::[Java Champion], I'm regularly link:/conferences[speaking] at conferences such as QCon, JavaOne, Red Hat Summit, JavaZone, JavaLand and Kafka Summit.

Occasionally, I link:/blog[blog] about topics related to software engineering.

== Speaker Information

**Bio:** Gunnar Morling is a software engineer and open-source enthusiast by heart, currently working at Decodable on stream processing based on Apache Flink. In his prior role as a software engineer at Red Hat, he led the Debezium project, a distributed platform for change data capture. He is a Java Champion and has founded multiple open source projects such as JfrUnit, kcctl, and MapStruct. Gunnar is an avid blogger (morling.dev) and has spoken at a wide range of conferences like QCon, Java One, and Devoxx. He lives in Hamburg, Germany.

**Head shot:** link:/images/gunnar_morling_500.jpg[500px], link:/images/gunnar_morling_1000.jpg[1000px]
