---
title: "How I Use (and Don't Use) AI"
date: 2025-06-19T09:30:00+02:00
draft: false
type: "page"
markup: adoc
---

When you read a post on this site, you can be sure it is an original article, written by a human: me.

My goal is to share unique (in any case, personal), and hopefully innovative perspectives, based on my own work and experience.
Large language models (LLMs) are not going to give you that.
I don't see much value in publishing articles written by an LLM;
after all, you could just run ChatGPT or Claude by yourself in order to do so.

This is not to say I am not working with AI in the process of writing at all.
I am using AI occassionally, similar to working with a human copy editor,
helping me to improve articles, once I have a draft.
The scope of this are light-touch changes, affecting a few handful of words.
Here is how I am using AI:

== What I Use AI For

* Checking for correct grammar and wording
* Making suggestions for improving the expressiveness of my language; being a non-native English speaker, I like for instance finding new words to add variety. Case in point: I tend to overuse the word "use" (just check this page ;), and AI helps to find alternatives
* Validating whether the line of thought of an article is coherent
* Making suggestions for article titles and teasers, which I rework substantially to focus on the right thing and match my personal voice

== What I Do Not Use AI For

* Original writing in any form
* Creating complete paragraphs or sections
